# IBM Developer Skills Network

# Long short-term memory in RNN for language modeling

<a id="language_modelling"></a>

<h2>What exactly is Language Modelling?</h2>
Language Modelling, to put it simply, <b>is the task of assigning probabilities to sequences of words</b>. This means that, given a context of one or a sequence of words in the language the model was trained on, the model should provide the next most probable words or sequence of words that follows from the given sequence of words the sentence. Language Modelling is one of the most important tasks in Natural Language Processing.

<img src="https://ibm.box.com/shared/static/1d1i5gub6wljby2vani2vzxp0xsph702.png" width="1080">
<center><i>Example of a sentence being predicted</i></center>
<br><br>
In this example, one can see the predictions for the next word of a sentence, given the context "This is an". As you can see, this boils down to a sequential data analysis task -- you are given a word or a sequence of words (the input data), and, given the context (the state), you need to find out what is the next word (the prediction). This kind of analysis is very important for language-related tasks such as <b>Speech Recognition, Machine Translation, Image Captioning, Text Correction</b> and many other very relevant problems. 

<img src="https://ibm.box.com/shared/static/az39idf9ipfdpc5ugifpgxnydelhyf3i.png" width="1080">
<center><i>The above example is a schema of an RNN in execution</i></center>
<br><br>
As the above image shows, Recurrent Network models fit this problem like a glove. Alongside LSTM and its capacity to maintain the model's state for over one thousand time steps, we have all the tools we need to undertake this problem. The goal for this notebook is to create a model that can reach <b>low levels of perplexity</b> on our desired dataset.

For Language Modelling problems, <b>perplexity</b> is the way to gauge efficiency. Perplexity is simply a measure of how well a probabilistic model is able to predict its sample. A higher-level way to explain this would be saying that <b>low perplexity means a higher degree of trust in the predictions the model makes</b>. Therefore, the lower perplexity is, the better.

<a id="treebank_dataset"></a>

<h2>The Penn Treebank dataset</h2>
Historically, datasets big enough for Natural Language Processing are hard to come by. This is in part due to the necessity of the sentences to be broken down and tagged with a certain degree of correctness -- or else the models trained on it won't be able to be correct at all. This means that we need a <b>large amount of data, annotated by or at least corrected by humans</b>. This is, of course, not an easy task at all.

The Penn Treebank, or PTB for short, is a dataset maintained by the University of Pennsylvania. It is <i>huge</i> -- there are over <b>four million and eight hundred thousand</b> annotated words in it, all corrected by humans. It is composed of many different sources, from abstracts of Department of Energy papers to texts from the Library of America. Since it is verifiably correct and of such a huge size, the Penn Treebank is commonly used as a benchmark dataset for Language Modelling.

The dataset is divided in different kinds of annotations, such as Piece-of-Speech, Syntactic and Semantic skeletons. For this example, we will simply use a sample of clean, non-annotated words (with the exception of one tag --<code>\<unk></code>
, which is used for rare words such as uncommon proper nouns) for our model. This means that we just want to predict what the next words would be, not what they mean in context or their classes on a given sentence.

<center>Example of text from the dataset we are going to use, <b>ptb.train</b></center>
<br><br>

<div class="alert alert-block alert-info" style="margin-top: 20px">
    <center>the percentage of lung cancer deaths among the workers at the west <code>&lt;unk&gt;</code> mass. paper factory appears to be the highest for any asbestos workers studied in western industrialized countries he said 
 the plant which is owned by <code>&lt;unk&gt;</code> & <code>&lt;unk&gt;</code> co. was under contract with <code>&lt;unk&gt;</code> to make the cigarette filters 
 the finding probably will support those who argue that the U.S. should regulate the class of asbestos including <code>&lt;unk&gt;</code> more <code>&lt;unk&gt;</code> than the common kind of asbestos <code>&lt;unk&gt;</code> found in most schools and other buildings dr. <code>&lt;unk&gt;</code> said</center>
</div>

<a id="word_embedding"></a>

<h2>Word Embeddings</h2><br/>

For better processing, in this example, we will make use of <a href="https://www.tensorflow.org/tutorials/word2vec/?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDL0120ENSkillsNetwork20629446-2021-01-01"><b>word embeddings</b></a>, which is <b>a way of representing sentence structures or words as n-dimensional vectors (where n is a reasonably high number, such as 200 or 500) of real numbers</b>. Basically, we will assign each word a randomly-initialized vector, and input those into the network to be processed. After a number of iterations, these vectors are expected to assume values that help the network to correctly predict what it needs to -- in our case, the probable next word in the sentence. This is shown to be a very effective task in Natural Language Processing, and is a commonplace practice. <br><br> <font size="4"><strong>

Word Embedding tends to group up similarly used words <i>reasonably</i> close together in the vectorial space. For example, if we use T-SNE (a dimensional reduction visualization algorithm) to flatten the dimensions of our vectors into a 2-dimensional space and plot these words in a 2-dimensional space, we might see something like this:

<img src="https://ibm.box.com/shared/static/bqhc5dg879gcoabzhxra1w8rkg3od1cu.png" width="800">
<center><i>T-SNE Mockup with clusters marked for easier visualization</i></center>
<br><br>
As you can see, words that are frequently used together, in place of each other, or in the same places as them tend to be grouped together -- being closer together the higher they are correlated. For example, "None" is pretty semantically close to "Zero", while a phrase that uses "Italy", you could probably also fit "Germany" in it, with little damage to the sentence structure. The vectorial "closeness" for similar words like this is a great indicator of a well-built model.

<hr>

We need to import the necessary modules for our code. We need <b><code>numpy</code></b> and <b><code>tensorflow</code></b>, obviously. Additionally, we can import directly the <b><code>tensorflow\.models.rnn</code></b> model, which includes the function for building RNNs, and <b><code>tensorflow\.models.rnn.ptb.reader</code></b> which is the helper module for getting the input data from the dataset we just downloaded.

If you want to learn more take a look at <https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/reader.py>


In [1]:
import time
import numpy as np
import tensorflow as tf
print(tf.__version__)

2.3.0


In [2]:
import sys
sys.path.insert(0, 'G:/Google Drive/My learning courses/Building Deep Learning Models with TensorFlow/data/ptb')

In [3]:
import reader

# Building the LSTM model for language Modeling

In [ ]:
# data source file
# http://www.fit.vutbr.cz/~imikolov/rnnlm/simple-examples.tgz 

## Hyper parameters

In [6]:
# initial weight scale
init_scale = 0.1
# initial learning rate
learning_rate = 1.0
# Maximum permissible norm for the gradient (For gradient clipping -- another measure against Exploding Gradients)
max_grad_norm = 5
# number of layers in model
num_layers = 2
# The total number of recurrence steps, also known as the number of layers when our RNN is "unfolded"
num_steps = 20
# The number of processing units (neurons) in the hidden layers
hidden_size_l1 = 256
hidden_size_l2 = 128
# The maximum number of epochs trained with the initial learning rate
max_epoch_decay_lr = 4
# The total number of epochs in training
max_epoch = 15
# The probability for keeping data in the Dropout Layer (This is an optimization, but is outside our scope for this notebook!)
# At 1, we ignore the Dropout Layer wrapping.
keep_prob = 1
# The decay for the learning rate
decay = 0.5
# The size for each batch of data
batch_size = 30
# the size of our vocabulary
vocab_size = 10000
embeding_vector_size = 200
# Training flag to separate training from testing
is_training = 1
# data directory for the dataset
data_dir = 'data/simple-examples/data/'

Some clarifications for LSTM architecture based on the arguments:

Network structure:

<ul>
    <li>In this network, the number of LSTM cells are 2. To give the model more expressive power, we can add multiple layers of LSTMs to process the data. The output of the first layer will become the input of the second and so on.
    </li>
    <li>The recurrence steps is 20, that is, when our RNN is "Unfolded", the recurrence step is 20.</li>   
    <li>the structure is like:
        <ul>
            <li>200 input units -> [200x200] Weight -> 200 Hidden units (first layer) -> [200x200] Weight matrix  -> 200 Hidden units (second layer) ->  [200] weight Matrix -> 200 unit output</li>
        </ul>
    </li>
</ul>
<br>

Input layer:

<ul>
    <li>The network has 200 input units.</li>
    <li>Suppose each word is represented by an embedding vector of dimensionality e=200. The input layer of each cell will have 200 linear units. These e=200 linear units are connected to each of the h=200 LSTM units in the hidden layer (assuming there is only one hidden layer, though our case has 2 layers).
    </li>
    <li>The input shape is [batch_size, num_steps], that is [30x20]. It will turn into [30x20x200] after embedding, and then 20x[30x200]
    </li>
</ul>
<br>

Hidden layer:

<ul>
    <li>Each LSTM has 200 hidden units which is equivalent to the dimensionality of the embedding words and output.</li>
</ul>
<br>

There is a lot to be done and a ton of information to process at the same time, so go over this code slowly. It may seem complex at first, but if you try to apply what you just learned about language modelling to the code you see, you should be able to understand it.

This code is adapted from the <a href="https://github.com/tensorflow/models?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDeveloperSkillsNetworkDL0120ENSkillsNetwork20629446-2021-01-01">PTBModel</a> example bundled with the TensorFlow source code.

<h3>Training data</h3>
The story starts from data:
<ul>
    <li>Train data is a list of words, of size 929589, represented by numbers, e.g. [9971, 9972, 9974, 9975,...]</li>
    <li>We read data as mini-batch of size b=30. Assume the size of each sentence is 20 words (num_steps = 20). Then it will take $floor(\frac{N}{b \times h})+1=1548$ iterations for the learner to go through all sentences once. Where N is the size of the list of words, b is batch size, and h is size of each sentence. So, the number of iterators is 1548
    </li>
    <li>Each batch data is read from train dataset of size 600, and shape of [30x20]</li>
</ul>

In [7]:
# Reads the data and separates it into training data, validation data and testing data
raw_data = reader.ptb_raw_data(data_dir)
train_data, valid_data, test_data, vocab, word_to_id = raw_data

In [8]:
len(train_data)

929589

In [9]:
def id_to_word(id_list):
    line = []
    for w in id_list:
        for word, wid in word_to_id.items():
            if wid == w:
                line.append(word)
        
    return line

print(id_to_word(train_data[0:100]))

['aer', 'banknote', 'berlitz', 'calloway', 'centrust', 'cluett', 'fromstein', 'gitano', 'guterman', 'hydro-quebec', 'ipo', 'kia', 'memotec', 'mlx', 'nahb', 'punts', 'rake', 'regatta', 'rubens', 'sim', 'snack-food', 'ssangyong', 'swapo', 'wachter', '<eos>', 'pierre', '<unk>', 'N', 'years', 'old', 'will', 'join', 'the', 'board', 'as', 'a', 'nonexecutive', 'director', 'nov.', 'N', '<eos>', 'mr.', '<unk>', 'is', 'chairman', 'of', '<unk>', 'n.v.', 'the', 'dutch', 'publishing', 'group', '<eos>', 'rudolph', '<unk>', 'N', 'years', 'old', 'and', 'former', 'chairman', 'of', 'consolidated', 'gold', 'fields', 'plc', 'was', 'named', 'a', 'nonexecutive', 'director', 'of', 'this', 'british', 'industrial', 'conglomerate', '<eos>', 'a', 'form', 'of', 'asbestos', 'once', 'used', 'to', 'make', 'kent', 'cigarette', 'filters', 'has', 'caused', 'a', 'high', 'percentage', 'of', 'cancer', 'deaths', 'among', 'a', 'group', 'of']


Lets just read one mini-batch now and feed our network:


In [10]:
itera = reader.ptb_iterator(train_data, batch_size, num_steps)
first_touple = itera.__next__()
_input_data = first_touple[0]
_targets = first_touple[1]

In [11]:
_input_data.shape

(30, 20)

In [12]:
_targets.shape

(30, 20)

Lets look at 3 sentences of our input x:

In [13]:
_input_data[0:3]

array([[9970, 9971, 9972, 9974, 9975, 9976, 9980, 9981, 9982, 9983, 9984,
        9986, 9987, 9988, 9989, 9991, 9992, 9993, 9994, 9995],
       [2654,    6,  334, 2886,    4,    1,  233,  711,  834,   11,  130,
         123,    7,  514,    2,   63,   10,  514,    8,  605],
       [   0, 1071,    4,    0,  185,   24,  368,   20,   31, 3109,  954,
          12,    3,   21,    2, 2915,    2,   12,    3,   21]])

In [14]:
print(id_to_word(_input_data[0,:]))

['aer', 'banknote', 'berlitz', 'calloway', 'centrust', 'cluett', 'fromstein', 'gitano', 'guterman', 'hydro-quebec', 'ipo', 'kia', 'memotec', 'mlx', 'nahb', 'punts', 'rake', 'regatta', 'rubens', 'sim']


<h3>Embeddings</h3>
We have to convert the words in our dataset to vectors of numbers. The traditional approach is to use one-hot encoding method that is usually used for converting categorical values to numerical values. However, One-hot encoded vectors are high-dimensional, sparse and in a big dataset, computationally inefficient. So, we use word2vec approach. It is, in fact, a layer in our LSTM network, where the word IDs will be represented as a dense representation before feeding to the LSTM. 

The embedded vectors also get updated during the training process of the deep neural network.
We create the embeddings for our input data. <b>embedding_vocab</b> is matrix of \[10000x200] for all 10000 unique words.

<b>embedding_lookup()</b> finds the embedded values for our batch of 30x20 words. It  goes to each row of <code>input_data</code>, and for each word in the row/sentence, finds the correspond vector in <code>embedding_dic<code>. <br>
It creates a \[30x20x200] tensor, so, the first element of <b>inputs</b> (the first sentence), is a matrix of 20x200, which each row of it, is vector representing a word in the sentence.


In [15]:
embedding_layer = tf.keras.layers.Embedding(vocab_size, 
                                            embeding_vector_size,
                                            batch_input_shape=(batch_size, num_steps),
                                            trainable=True,name="embedding_vocab")                                  

In [16]:
# Define where to get the data for our embeddings from
inputs = embedding_layer(_input_data)
inputs

<tf.Tensor: shape=(30, 20, 200), dtype=float32, numpy=
array([[[-4.9137056e-02,  1.8777478e-02, -3.6913227e-02, ...,
          1.9667160e-02,  8.4553249e-03, -3.7688423e-02],
        [-3.3282995e-02, -1.6821824e-02, -2.7668942e-02, ...,
          2.9118434e-03, -4.0627234e-03,  4.8960719e-02],
        [-3.0993773e-02,  6.2788017e-03, -7.4289925e-03, ...,
         -7.6216236e-03,  3.2822005e-03,  1.5959632e-02],
        ...,
        [-1.7862320e-02, -9.1356039e-03, -4.0644348e-02, ...,
         -3.3646822e-03, -1.4557727e-03,  4.2036425e-02],
        [-4.1359972e-02,  2.3119736e-02,  3.0206926e-03, ...,
         -3.0699968e-03, -4.7694873e-02,  2.1572534e-02],
        [ 1.2960102e-02, -1.1052825e-02, -3.1306863e-02, ...,
         -1.3282932e-02,  9.4322935e-03,  4.1511681e-02]],

       [[-2.3052549e-02,  1.0255445e-02, -1.4926098e-02, ...,
         -6.0045943e-03, -4.1688133e-02,  2.5959622e-02],
        [-2.7869655e-02, -2.9658962e-02, -4.2539861e-02, ...,
         -3.2344151e-02,  3.

# Constructing Recurrent Neural Network

In this step, we create the stacked LSTM using <b>tf.keras.layers.StackedRNNCells</b>, which is a 2 layer LSTM network:


In [17]:
lstm_cell_l1 = tf.keras.layers.LSTMCell(hidden_size_l1)
lstm_cell_l2 = tf.keras.layers.LSTMCell(hidden_size_l2)

In [18]:
stacked_lstm = tf.keras.layers.StackedRNNCells([lstm_cell_l1, lstm_cell_l2])

The input should be a Tensor of shape: \[batch_size, max_time, embedding_vector_size], in our case it would be (30, 20, 200)


In [19]:
layer = tf.keras.layers.RNN(stacked_lstm, 
                            [batch_size, num_steps],
                            return_state=False,
                            stateful=True,
                            trainable=True)                        

Also, we initialize the states of the nework:

<h4>_initial_state</h4>

For each LSTM, there are 2 state matrices, c_state and m_state.  c_state and m_state represent "Memory State" and "Cell State". Each hidden layer, has a vector of size 30, which keeps the states. so, for 200 hidden units in each LSTM, we have a matrix of size \[30x200]

In [20]:
init_state = tf.Variable(tf.zeros([batch_size, embeding_vector_size]), trainable=False)

In [21]:
layer.initial_state = init_state

In [22]:
layer.initial_state

<tf.Variable 'Variable:0' shape=(30, 200) dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>

so, lets look at the outputs. The output of the stackedLSTM comes from 128 hidden_layer, and in each time step(=20), one of them get activated. we use the linear activation to map the 128 hidden layer to a \[30X20 matrix]

In [23]:
outputs = layer(inputs)

In [24]:
outputs

<tf.Tensor: shape=(30, 20, 128), dtype=float32, numpy=
array([[[-1.9734839e-03,  1.2062625e-03,  1.0742216e-03, ...,
          2.3005425e-03,  1.2232426e-03, -5.3291576e-04],
        [-2.9973635e-03,  3.9102626e-03, -7.5239391e-04, ...,
          4.0363623e-03,  2.7067710e-03, -1.2758434e-03],
        [-2.8832271e-03,  5.2068792e-03, -1.5169213e-03, ...,
          4.4344342e-03,  3.6913010e-03, -1.9038805e-03],
        ...,
        [-2.6147638e-03,  4.2373445e-03, -2.4586662e-03, ...,
          3.9972421e-03, -7.0712704e-05,  3.6794404e-03],
        [-1.4702071e-03,  4.4479491e-03, -2.5923972e-03, ...,
          4.9374038e-03, -1.1578345e-04,  3.4882706e-03],
        [ 8.7832205e-04,  4.6055010e-03, -2.1575706e-03, ...,
          4.0897625e-03, -2.8138375e-04,  2.7624583e-03]],

       [[-1.6032370e-04, -1.9462215e-04,  1.1219928e-03, ...,
          1.1451787e-03, -6.4601935e-04, -6.3797284e-04],
        [-1.3625690e-03,  1.2040679e-04,  1.2591780e-03, ...,
          2.8071655e-03, -1.

# Dense Layer

We now create densely-connected neural network layer that would reshape the outputs tensor from  [30 x 20 x 128] to [30 x 20 x 10000].


In [25]:
dense = tf.keras.layers.Dense(vocab_size)

In [26]:
logits_outputs = dense(outputs)

In [27]:
print("shape of the output from dense layer: ", logits_outputs.shape) #(batch_size, sequence_length, vocab_size)

shape of the output from dense layer:  (30, 20, 10000)


# Activation layer

A softmax activation layers is also then applied to derive the probability of the output being in any of the multiclass(10000 in this case) possibilities.

In [28]:
activation = tf.keras.layers.Activation('softmax')

In [29]:
output_words_prob = activation(logits_outputs)

print("shape of the output from the activation layer: ", output_words_prob.shape) #(batch_size, sequence_length, vocab_size)

Lets look at the probability of observing words for t=0 to t=20:


In [30]:
print("The probability of observing words in t=0 to t=20", output_words_prob[0,0:num_steps])

The probability of observing words in t=0 to t=20 tf.Tensor(
[[1.00005156e-04 1.00014848e-04 9.99845142e-05 ... 9.99795084e-05
  9.99891054e-05 9.99836120e-05]
 [1.00014346e-04 9.99973345e-05 9.99732511e-05 ... 9.99499971e-05
  1.00000871e-04 9.99705444e-05]
 [1.00034362e-04 9.99930271e-05 9.99667245e-05 ... 9.99347103e-05
  1.00029079e-04 1.00004152e-04]
 ...
 [1.00071666e-04 9.99250115e-05 9.99584809e-05 ... 1.00010926e-04
  1.00038473e-04 1.00032681e-04]
 [1.00054829e-04 9.99442927e-05 9.99547192e-05 ... 9.99894255e-05
  1.00035053e-04 1.00020181e-04]
 [1.00044897e-04 9.99502954e-05 9.99659096e-05 ... 9.99536205e-05
  1.00044665e-04 1.00012112e-04]], shape=(20, 10000), dtype=float32)


# Prediction

In [31]:
np.argmax(output_words_prob[0, 0:num_steps], axis=1)

array([6970, 2683, 6086, 6086, 2760, 1855, 5103, 5103, 5103, 6179, 6179,
       6179, 6179, 6179, 1313, 1313, 1313, 9086, 9086, 6298], dtype=int64)

So, what is the ground truth for the first word of first sentence? You can get it from target tensor, if you want to find the embedding vector:

In [32]:
_targets[0]

array([9971, 9972, 9974, 9975, 9976, 9980, 9981, 9982, 9983, 9984, 9986,
       9987, 9988, 9989, 9991, 9992, 9993, 9994, 9995, 9996])

# Objective function

How similar the predicted words are to the target words?

Now we have to define our objective function, to calculate the similarity of predicted values to ground truth, and then, penalize the model with the error. Our objective is to minimize loss function, that is, to minimize the average negative log probability of the target words:

$$\text{loss} = -\frac{1}{N}\sum\_{i=1}^{N} \ln p\_{\text{target}\_i}$$

This function is already implemented and available in TensorFlow through *tf.keras.losses.sparse_categorical_crossentropy*. It calculates the categorical cross-entropy loss for <b>logits</b> and the <b>target</b> sequence.

The arguments of this function are:

<ul>
    <li>logits: List of 2D Tensors of shape [batch_size x num_decoder_symbols].</li>  
    <li>targets: List of 1D batch-sized int32 Tensors of the same length as logits.</li>   
</ul>


In [33]:
def crossentropy(y_true, y_pred):
    return tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)

In [34]:
loss = crossentropy(_targets, output_words_prob)

In [35]:
# 1st 10 values of losses
loss[0,:10]

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([9.210213, 9.210423, 9.210902, 9.209682, 9.209731, 9.210162,
       9.21006 , 9.209985, 9.209789, 9.210582], dtype=float32)>

In [36]:
# cost a average value of loss
cost = tf.reduce_sum(loss/batch_size)
cost

<tf.Tensor: shape=(), dtype=float32, numpy=184.20628>

<h3>Training</h3>

To do training for our network, we have to take the following steps:

<ol>
    <li>Define the optimizer.</li>
    <li>Assemble layers to build model.</li>
    <li>Calculate the gradients based on the loss function.</li>
    <li>Apply the optimizer to the variables/gradients tuple.</li>
</ol>


## 1. Define optimizer

In [37]:
lr = tf.Variable(0.0, trainable=False)
optimizer = tf.keras.optimizers.SGD(lr=lr, clipnorm=max_grad_norm)

## 2. Assemble layers to build model

In [38]:
model = tf.keras.Sequential()
model.add(embedding_layer)
model.add(layer)
model.add(dense)
model.add(activation)
model.compile(loss=crossentropy, optimizer=optimizer)
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_vocab (Embedding)  (30, 20, 200)             2000000   
_________________________________________________________________
rnn (RNN)                    (30, 20, 128)             671088    
_________________________________________________________________
dense (Dense)                (30, 20, 10000)           1290000   
_________________________________________________________________
activation (Activation)      (30, 20, 10000)           0         
Total params: 3,961,088
Trainable params: 3,955,088
Non-trainable params: 6,000
_________________________________________________________________


## 3. Trainable parameters

Defining a variable, if you passed <i>trainable=True</i>, the variable constructor automatically adds new variables to the graph collection <b>GraphKeys.TRAINABLE_VARIABLES</b>. Now, using <i>tf.trainable_variables()</i> you can get all variables created with <b>trainable=True</b>.

In [39]:
# Get all trainables parameters
tvars = model.trainable_variables

In [40]:
[v.name for v in tvars]

['embedding_vocab/embeddings:0',
 'rnn/stacked_rnn_cells/lstm_cell/kernel:0',
 'rnn/stacked_rnn_cells/lstm_cell/recurrent_kernel:0',
 'rnn/stacked_rnn_cells/lstm_cell/bias:0',
 'rnn/stacked_rnn_cells/lstm_cell_1/kernel:0',
 'rnn/stacked_rnn_cells/lstm_cell_1/recurrent_kernel:0',
 'rnn/stacked_rnn_cells/lstm_cell_1/bias:0',
 'dense/kernel:0',
 'dense/bias:0']

## 4. Calculate the gradient based on the loss function

**Gradient**: The gradient of a function is the slope of its derivative (line), or in other words, the rate of change of a function. It's a vector (a direction to move) that points in the direction of greatest increase of the function, and calculated by the <b>derivative</b> operation.

First lets recall the gradient function using an toy example:
$$ z = \left(2x^2 + 3xy\right)$$

In [41]:
x = tf.constant(1.0)
y =  tf.constant(2.0)
with tf.GradientTape(persistent=True) as g:
    g.watch(x)
    g.watch(y)
    func_test = 2 * x * x + 3 * x * y

The <b>tf.gradients()</b> function allows you to compute the symbolic gradient of one tensor with respect to one or more other tensors—including variables. <b>tf.gradients(func, xs)</b> constructs symbolic partial derivatives of sum of <b>func</b> w\.r.t. <i>x</i> in <b>xs</b>.

Now, lets look at the derivitive w\.r.t. <b>var_x</b>:
$$ \frac{\partial :}{\partial \:x}\left(2x^2 + 3xy\right) = 4x + 3y $$

In [42]:
var_grad = g.gradient(func_test, x)
print(var_grad)

tf.Tensor(10.0, shape=(), dtype=float32)


In [43]:
var_grad = g.gradient(func_test, y) # Will compute to 3.0
print(var_grad)

tf.Tensor(3.0, shape=(), dtype=float32)


In [44]:
with tf.GradientTape() as tape:
    # Forward pass
    output_words_prob = model(_input_data)
    # Loss value for this batch
    loss = crossentropy(_targets, output_words_prob)
    cost = tf.reduce_sum(loss, axis=0) / batch_size

In [45]:
# Get gradients of loss with the parameters
grad_t_list = tape.gradient(cost, tvars)

In [47]:
print(grad_t_list[0])

IndexedSlices(indices=tf.Tensor(
[9970 9971 9972 9974 9975 9976 9980 9981 9982 9983 9984 9986 9987 9988
 9989 9991 9992 9993 9994 9995 2654    6  334 2886    4    1  233  711
  834   11  130  123    7  514    2   63   10  514    8  605    0 1071
    4    0  185   24  368   20   31 3109  954   12    3   21    2 2915
    2   12    3   21    3   71    4   27  246   60   11  215    4    1
 1846    9    3   71  546    2 6505  162    6  104   93   25    6  261
  681  251    0  278 3246   13  200    1    8  105 3360    1    4    0
  536    4   20    6  954   12    3   21   78   14  977  726    0   37
   42   34    5  437  116  206  927    2   18  296    7  201   76    4
  182  560 3836   17  974  975    6  942    4  156   77 1570  288  644
   23 1238  899    5   25  201    4    0  434  642   55  201    4    0
 2423    2    1    1    1  483  379  706    9  413 8219   96   15    0
 2185 1758    1    1   37   13  834    5  852  222    7 1785    2  179
  940  117   38   59  677   14    1   10 101

now, we have a list of tensors, t-list. We can use it to find clipped tensors. <b>clip_by_global_norm</b> clips values of multiple tensors by the ratio of the sum of their norms.

<b>clip_by_global_norm</b> get <i>t-list</i> as input and returns 2 things:

<ul>
    <li>a list of clipped tensors, so called <i>list_clipped</i></li> 
    <li>the global norm (global_norm) of all tensors in t_list</li> 
</ul>


In [50]:
# define the gradient clipping threshold
grads, _ = tf.clip_by_global_norm(grad_t_list, max_grad_norm)
grads[1]

<tf.Tensor: shape=(200, 1024), dtype=float32, numpy=
array([[ 2.2543196e-07,  6.8046484e-07,  1.6646533e-07, ...,
        -4.8608416e-07,  7.0475863e-08, -1.0642000e-06],
       [-9.8070757e-08,  2.6930968e-07, -2.5278615e-07, ...,
        -2.9163294e-07, -2.1874058e-08, -7.0386045e-07],
       [ 7.1161014e-07, -3.6459028e-08,  1.9264365e-07, ...,
        -2.5742187e-07, -1.7866209e-07,  2.1103287e-07],
       ...,
       [ 2.9839717e-07,  6.6508716e-07,  3.1229368e-07, ...,
         1.6184237e-07,  1.6464455e-07, -3.6590029e-07],
       [ 4.7415378e-07,  1.5711742e-06, -5.8572638e-08, ...,
         8.0207627e-08, -8.4898247e-08,  2.6870643e-07],
       [ 2.2503616e-07, -5.3138541e-07,  3.9376945e-07, ...,
        -1.2028498e-07, -2.1003255e-07,  2.6719181e-07]], dtype=float32)>

## 5. Apply the optimizer to the variables/ gradients tuple

In [51]:
# Create the training TensorFlow Operation through our optimizer
train_op = optimizer.apply_gradients(zip(grads, tvars))

<a id="ltsm"></a>

<h2>LSTM</h2>


We learned how the model is build step by step. Now, let's then create a Class that represents our model. This class needs a few things:

<ul>
    <li>We have to create the model in accordance with our defined hyperparameters</li>
    <li>We have to create the LSTM cell structure and connect them with our RNN structure</li>
    <li>We have to create the word embeddings and point them to the input data</li>
    <li>We have to create the input structure for our RNN</li>
    <li>We need to create a logistic structure to return the probability of our words</li>
    <li>We need to create the loss and cost functions for our optimizer to work, and then create the optimizer</li>
    <li>And finally, we need to create a training operation that can be run to actually train our model</li>
</ul>

In [52]:
class PTBModel(object):


    def __init__(self):
    
        # Setting parameters for ease of use #
        #     
        self.batch_size = batch_size
        self.num_steps = num_steps
        self.hidden_size_l1 = hidden_size_l1
        self.hidden_size_l2 = hidden_size_l2
        self.vocab_size = vocab_size
        self.embeding_vector_size = embeding_vector_size
        # Create a variable for the learning rate
        self._lr = 1.0
        
        # Initializing the model using keras Sequential API  #
        
        self._model = tf.keras.models.Sequential()
           
        # Creating the word embeddings layer and adding it to the sequence #
     
        with tf.device("/cpu:0"):
            # Create the embeddings for our input data. Size is hidden size.
            self._embedding_layer = tf.keras.layers.Embedding(self.vocab_size, 
                                                              self.embeding_vector_size,
                                                              batch_input_shape=(self.batch_size, self.num_steps),
                                                              trainable=True,
                                                              name="embedding_vocab")  #[10000x200]
            self._model.add(self._embedding_layer)            

  
        # Creating the LSTM cell structure and connect it with the RNN structure #
 
        # Create the LSTM Cells. 
        # This creates only the structure for the LSTM and has to be associated with a RNN unit still.
        # The argument  of LSTMCell is size of hidden layer, that is, the number of hidden units of the LSTM (inside A). 
        # LSTM cell processes one word at a time and computes probabilities of the possible continuations of the sentence.
        lstm_cell_l1 = tf.keras.layers.LSTMCell(hidden_size_l1)
        lstm_cell_l2 = tf.keras.layers.LSTMCell(hidden_size_l2)       

        
        # By taking in the LSTM cells as parameters, the StackedRNNCells function junctions the LSTM units to the RNN units.
        # RNN cell composed sequentially of stacked simple cells.
        stacked_lstm = tf.keras.layers.StackedRNNCells([lstm_cell_l1, lstm_cell_l2])
        
     
        # Creating the input structure for our RNN #
       
        # Input structure is 20x[30x200]
        # Considering each word is represended by a 200 dimentional vector, and we have 30 batchs, we create 30 word-vectors of size [30xx2000]
        # The input structure is fed from the embeddings, which are filled in by the input data
        # Feeding a batch of b sentences to a RNN:
        # In step 1,  first word of each of the b sentences (in a batch) is input in parallel.  
        # In step 2,  second word of each of the b sentences is input in parallel. 
        # The parallelism is only for efficiency.  
        # Each sentence in a batch is handled in parallel, but the network sees one word of a sentence at a time and does the computations accordingly. 
        # All the computations involving the words of all sentences in a batch at a given time step are done in parallel. 
 
        # Instantiating our RNN model and setting stateful to True to feed forward the state to the next layer #     
        
        self._RNNlayer  =  tf.keras.layers.RNN(stacked_lstm,
                                              [batch_size, num_steps],
                                              return_state=False,
                                              stateful=True,
                                              trainable=True)
        
        # Define the initial state, i.e., the model state for the very first data point
        # It initialize the state of the LSTM memory. The memory state of the network is initialized with a vector of zeros and gets updated after reading each word.
        self._initial_state = tf.Variable(tf.zeros([batch_size,embeding_vector_size]),trainable=False)
        self._RNNlayer.inital_state = self._initial_state
    

        # Adding RNN layer to keras sequential API #
   
        self._model.add(self._RNNlayer)
        
        #self._model.add(tf.keras.layers.LSTM(hidden_size_l1,return_sequences=True,stateful=True))
        #self._model.add(tf.keras.layers.LSTM(hidden_size_l2,return_sequences=True))                
     
        # Instantiating a Dense layer that connects the output to the vocab_size  and adding layer to model#
      
        self._dense = tf.keras.layers.Dense(self.vocab_size)
        self._model.add(self._dense)         
    
        # Adding softmax activation layer and deriving probability to each class and adding layer to model #
    
        self._activation = tf.keras.layers.Activation('softmax')
        self._model.add(self._activation)
    
        # Instantiating the stochastic gradient decent optimizer #
     
        self._optimizer = tf.keras.optimizers.SGD(lr=self._lr, clipnorm=max_grad_norm)
                    
        # Compiling and summarizing the model stacked using the keras sequential API #
 
        self._model.compile(loss=self.crossentropy, optimizer=self._optimizer)
        self._model.summary()


    def crossentropy(self,y_true, y_pred):
        return tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)

    def train_batch(self,_input_data,_targets):

        # Creating the Training Operation for our Model #
     
        # Create a variable for the learning rate
        self._lr = tf.Variable(0.0, trainable=False)
        # Get all TensorFlow variables marked as "trainable" (i.e. all of them except _lr, which we just created)
        tvars = self._model.trainable_variables
        # Define the gradient clipping threshold
        with tf.GradientTape() as tape:
            # Forward pass.
            output_words_prob = self._model(_input_data)
            # Loss value for this batch.
            loss  = self.crossentropy(_targets, output_words_prob)
            # average across batch and reduce sum
            cost = tf.reduce_sum(loss/ self.batch_size)
        # Get gradients of loss wrt the trainable variables.
        grad_t_list = tape.gradient(cost, tvars)
        # Define the gradient clipping threshold
        grads, _ = tf.clip_by_global_norm(grad_t_list, max_grad_norm)
        # Create the training TensorFlow Operation through our optimizer
        train_op = self._optimizer.apply_gradients(zip(grads, tvars))
        return cost
        
    def test_batch(self,_input_data,_targets):
     
        # Creating the Testing Operation for our Model #
     
        output_words_prob = self._model(_input_data)
        loss  = self.crossentropy(_targets, output_words_prob)
        # average across batch and reduce sum
        cost = tf.reduce_sum(loss/ self.batch_size)

        return cost
    @classmethod
    def instance(cls) : 
        return PTBModel()

With that, the actual structure of our Recurrent Neural Network with Long Short-Term Memory is finished. What remains for us to do is to actually create the methods to run through time -- that is, the <code>run_epoch</code> method to be run at each epoch and a <code>main</code> script which ties all of this together.

What our <code>run_epoch</code> method should do is take our input data and feed it to the relevant operations. This will return at the very least the current result for the cost function.

In [53]:
# run_one_epoch takes as parameters  the model instance, the data to be fed, training or testing mode and verbose info #

def run_one_epoch(m, data,is_training=True,verbose=False):

    #Define the epoch size based on the length of the data, batch size and the number of steps
    epoch_size = ((len(data) // m.batch_size) - 1) // m.num_steps
    start_time = time.time()
    costs = 0.
    iters = 0
    
    m._model.reset_states()
    
    #For each step and data point
    for step, (x, y) in enumerate(reader.ptb_iterator(data, m.batch_size, m.num_steps)):
        
        #Evaluate and return cost, state by running cost, final_state and the function passed as parameter
        #y = tf.keras.utils.to_categorical(y, num_classes=vocab_size)
        if is_training : 
            loss=  m.train_batch(x, y)
        else :
            loss = m.test_batch(x, y)
                                   
        #Add returned cost to costs (which keeps track of the total costs for this epoch)
        costs += loss
        
        #Add number of steps to iteration counter
        iters += m.num_steps

        if verbose and step % (epoch_size // 10) == 10:
            print("Itr %d of %d, perplexity: %.3f speed: %.0f wps" % (step , epoch_size, np.exp(costs / iters), iters * m.batch_size / (time.time() - start_time)))
        

    # Returns the Perplexity rating for us to keep track of how the model is evolving
    return np.exp(costs / iters)

In [54]:
# Reads the data and separates it into training data, validation data and testing data
raw_data = reader.ptb_raw_data(data_dir)
train_data, valid_data, test_data, _, _ = raw_data

In [55]:
# Instantiates the PTBModel class
m=PTBModel.instance()   
K = tf.keras.backend 

for i in range(max_epoch):
    # Define the decay for this epoch
    lr_decay = decay ** max(i - max_epoch_decay_lr, 0.0)
    dcr = learning_rate * lr_decay
    m._lr = dcr
    K.set_value(m._model.optimizer.learning_rate,m._lr)
    print("Epoch %d : Learning rate: %.3f" % (i + 1, m._model.optimizer.learning_rate))
    # Run the loop for this epoch in the training mode
    train_perplexity = run_one_epoch(m, train_data,is_training=True,verbose=True)
    print("Epoch %d : Train Perplexity: %.3f" % (i + 1, train_perplexity))
        
    # Run the loop for this epoch in the validation mode
    valid_perplexity = run_one_epoch(m, valid_data,is_training=False,verbose=False)
    print("Epoch %d : Valid Perplexity: %.3f" % (i + 1, valid_perplexity))
    
# Run the loop in the testing mode to see how effective was our training
test_perplexity = run_one_epoch(m, test_data,is_training=False,verbose=False)
print("Test Perplexity: %.3f" % test_perplexity)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_vocab (Embedding)  (30, 20, 200)             2000000   
_________________________________________________________________
rnn_1 (RNN)                  (30, 20, 128)             671088    
_________________________________________________________________
dense_1 (Dense)              (30, 20, 10000)           1290000   
_________________________________________________________________
activation_1 (Activation)    (30, 20, 10000)           0         
Total params: 3,961,088
Trainable params: 3,955,088
Non-trainable params: 6,000
_________________________________________________________________
Epoch 1 : Learning rate: 1.000
Itr 10 of 1549, perplexity: 5519.082 speed: 804 wps
Itr 164 of 1549, perplexity: 1089.362 speed: 824 wps
Itr 318 of 1549, perplexity: 837.922 speed: 824 wps
Itr 472 of 1549, perplexity: 688.189 speed: 823 wp

As you can see, the model's perplexity rating drops very quickly after a few iterations. As was elaborated before, <b>lower Perplexity means that the model is more certain about its prediction</b>. As such, we can be sure that this model is performing well!


This is the end of the <b>Applying Recurrent Neural Networks to Text Processing</b> notebook. Hopefully you now have a better understanding of Recurrent Neural Networks and how to implement one utilizing TensorFlow. Thank you for reading this notebook, and good luck on your studies.
